import asyncio
import json
from datetime import datetime, timezone
from fastapi import FastAPI, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, Response
from core.sse_manager import SSEManager
from core.orchestrator import run_scan

app = FastAPI(title="CodeSentinel", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

SUGGESTED_REPOS = [
    {
        "name": "OWASP Juice Shop",
        "url": "https://github.com/juice-shop/juice-shop.git",
        "description": "Deliberately vulnerable Node.js application",
    },
    {
        "name": "OWASP WebGoat",
        "url": "https://github.com/WebGoat/WebGoat.git",
        "description": "Deliberately vulnerable Java application",
    },
    {
        "name": "DVWA",
        "url": "https://github.com/digininja/DVWA.git",
        "description": "Damn Vulnerable Web Application (PHP)",
    },
]


@app.get("/api/health")
async def health():
    return {"status": "ok", "service": "CodeSentinel"}


@app.get("/api/repos/suggested")
async def suggested_repos():
    return {"repos": SUGGESTED_REPOS}


@app.get("/api/scan")
async def scan(repo_url: str = Query(..., description="Git repository URL to scan")):
    sse = SSEManager()

    async def run_in_background():
        await run_scan(repo_url, sse)

    asyncio.create_task(run_in_background())

    return StreamingResponse(
        sse.generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@app.post("/api/report")
async def generate_report(request: Request):
    """Generate a PDF security report with attack graph, findings, and fixes."""
    import base64
    import io
    import tempfile
    from fpdf import FPDF

    data = await request.json()
    findings = data.get("findings", [])
    patches = data.get("patches", [])
    summary = data.get("summary", {})
    repo_url = data.get("repo_url", "Unknown")
    graph_image = data.get("graph_image", "")  # base64 PNG from frontend

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    SEV_COLORS = {
        "CRITICAL": (255, 0, 51),
        "HIGH": (255, 102, 0),
        "MEDIUM": (255, 214, 0),
        "LOW": (74, 122, 0),
    }

    class Report(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 10)
            self.set_text_color(118, 185, 0)
            self.cell(0, 8, "CodeSentinel Security Report", ln=True, align="R")
            self.set_draw_color(42, 42, 42)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by CodeSentinel", align="C")

        def section_title(self, title):
            self.set_font("Helvetica", "B", 14)
            self.set_text_color(118, 185, 0)
            self.ln(6)
            self.cell(0, 8, title, ln=True)
            self.set_draw_color(118, 185, 0)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(4)

        def severity_badge(self, severity):
            color = SEV_COLORS.get(severity, (100, 100, 100))
            self.set_fill_color(*color)
            self.set_text_color(255, 255, 255)
            self.set_font("Helvetica", "B", 8)
            w = self.get_string_width(severity) + 6
            self.cell(w, 5, severity, fill=True, ln=0)
            self.set_text_color(30, 30, 30)
            self.cell(3, 5, "", ln=0)

    pdf = Report()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(118, 185, 0)
    pdf.cell(0, 15, "CodeSentinel", ln=True, align="C")
    pdf.set_font("Helvetica", "I", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, "Not a scanner. A researcher.", ln=True, align="C")
    pdf.ln(8)

    # Meta info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 5, f"Repository: {repo_url}", ln=True)
    pdf.cell(0, 5, f"Generated: {now}", ln=True)
    pdf.cell(0, 5, f"Files scanned: {summary.get('files_scanned', 'N/A')}  |  Duration: {summary.get('duration_seconds', 'N/A')}s", ln=True)
    pdf.ln(4)

    # Summary table
    pdf.section_title("Summary")
    pdf.set_font("Helvetica", "", 10)

    sev_counts = {}
    for f in findings:
        s = f.get("severity", "UNKNOWN")
        sev_counts[s] = sev_counts.get(s, 0) + 1

    by_source = summary.get("by_source", {})
    summary_rows = [
        ("Total Findings", str(summary.get("total_findings", len(findings)))),
        ("Exposed Secrets", str(by_source.get("secrets", 0))),
        ("Dependency CVEs", str(by_source.get("osv", 0))),
        ("Code Vulnerabilities", str(by_source.get("code", 0))),
        ("Patches Generated", str(summary.get("patches_generated", len(patches)))),
    ]

    for label, val in summary_rows:
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(80, 80, 80)
        pdf.cell(60, 6, label, border="B")
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 6, val, border="B", ln=True)

    pdf.ln(2)
    # Severity bar
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        count = sev_counts.get(sev, 0)
        if count:
            pdf.severity_badge(sev)
            pdf.set_font("Helvetica", "", 10)
            pdf.cell(0, 5, f"  {count}", ln=True)
    pdf.ln(2)

    # Attack Graph image
    if graph_image:
        pdf.section_title("Vulnerability Map")
        try:
            img_data = base64.b64decode(graph_image.split(",")[1] if "," in graph_image else graph_image)
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                tmp.write(img_data)
                tmp_path = tmp.name
            pdf.image(tmp_path, x=10, w=190)
            import os
            os.unlink(tmp_path)
        except Exception:
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 6, "(Attack graph image unavailable)", ln=True)
    pdf.ln(4)

    # Build patch lookup
    patch_map = {}
    for p in patches:
        patch_map[p.get("vuln_id", "")] = p

    # Findings
    secrets = [f for f in findings if f.get("source") == "secrets"]
    cves = [f for f in findings if f.get("source") == "osv"]
    code_vulns = [f for f in findings if f.get("source") == "code" or f.get("cwe_id")]

    def write_finding(f, include_patch=True):
        pdf.ln(2)
        pdf.severity_badge(f.get("severity", "?"))
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        title = f.get("title", "")
        if len(title) > 80:
            title = title[:80] + "..."
        pdf.cell(0, 5, f"  {title}", ln=True)

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)

        file_loc = f.get("file", "")
        if f.get("line_start"):
            file_loc += f":{f['line_start']}"
        elif f.get("line"):
            file_loc += f":{f['line']}"
        pdf.cell(0, 4, f"File: {file_loc}", ln=True)

        if f.get("cwe_id"):
            pdf.cell(0, 4, f"CWE: {f['cwe_id']} ({f.get('cwe_name', '')})", ln=True)

        if f.get("confidence"):
            pdf.cell(0, 4, f"Confidence: {f['confidence']}", ln=True)

        desc = f.get("description", "")
        if desc:
            pdf.ln(1)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 4, desc[:500])

        if f.get("evidence"):
            pdf.ln(1)
            pdf.set_font("Courier", "", 8)
            pdf.set_fill_color(245, 245, 245)
            pdf.set_text_color(30, 30, 30)
            evidence = f["evidence"][:400]
            for line in evidence.split("\n"):
                pdf.cell(0, 3.5, "  " + line[:120], ln=True, fill=True)
            pdf.set_font("Helvetica", "", 9)

        if f.get("data_flow_trace"):
            pdf.ln(1)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(0, 150, 200)
            pdf.multi_cell(0, 3.5, f"Data Flow: {f['data_flow_trace'][:200]}")

        if f.get("exploitation_scenario"):
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(200, 80, 0)
            pdf.multi_cell(0, 3.5, f"Exploitation: {f['exploitation_scenario'][:200]}")

        # Inline patch
        if include_patch:
            p = patch_map.get(f.get("id", ""))
            if p:
                pdf.ln(1)
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(118, 185, 0)
                pdf.cell(0, 4, "Recommended Fix:", ln=True)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(50, 50, 50)
                if p.get("explanation"):
                    pdf.multi_cell(0, 3.5, p["explanation"][:300])
                if p.get("patched_code"):
                    pdf.set_font("Courier", "", 7)
                    pdf.set_fill_color(240, 255, 240)
                    for line in p["patched_code"][:300].split("\n"):
                        pdf.cell(0, 3.5, "  " + line[:120], ln=True, fill=True)
                if p.get("commands"):
                    pdf.set_font("Courier", "", 8)
                    for cmd in p["commands"][:3]:
                        pdf.cell(0, 4, f"  $ {cmd}", ln=True)

        pdf.set_draw_color(220, 220, 220)
        pdf.ln(2)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    if code_vulns:
        pdf.section_title(f"Code Vulnerabilities ({len(code_vulns)})")
        for f in code_vulns:
            write_finding(f)

    if secrets:
        pdf.section_title(f"Exposed Secrets ({len(secrets)})")
        for f in secrets:
            write_finding(f)

    if cves:
        pdf.section_title(f"Dependency CVEs ({len(cves)})")
        for f in cves:
            write_finding(f)

    # Footer
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, "Generated by CodeSentinel - Not a scanner. A researcher.", ln=True, align="C")

    pdf_bytes = pdf.output()
    filename = f"codesentinel-report-{datetime.now().strftime('%Y%m%d-%H%M%S')}.pdf"

    return Response(
        content=bytes(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
